spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver;MODE=PostgreSQL
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: