server:
  port: 8080

spring:
  redis:
    client-name: simple-redis
    host: localhost
    database: 0
    port: 6379
    password:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat

open-api:
  kakao:
    rest-api-key: ${REST_API_KEY:KakaoAK d15462d4c14f493018e5b19707091ee1}
    base-url: ${KAKAO_BASE_URL:https://dapi.kakao.com}
    search-place-url: ${KAKAO_SEARCH_place_URL:/v2/local/search/keyword.json}
  naver:
    x-naver-client-id: ${X_NAVER_CLIENT_ID:yfRLHKsG3I84d3_ZKJnO}
    x-naver-client-secret: ${X_NAVER_CLINET_SECRET:jtjxz0Vsyi}
    base-url: ${NAVER_BASE_URL:https://openapi.naver.com}
    search-place-url: ${NAVER_SERACH_PLACE_URL:/v1/search/local.json}

basic:
  service-name: ${SERVICE_NAME:yebali_search_place}
  health-check-path: ${HEALTH_CHECK_PATH:/test/alive}

management:
  endpoint:
    loggers.enabled: true
    info.enabled: true
    health.enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: ""
      exposure:
        include: info, loggers, health
      path-mapping:
        info: /dominus/actuator/info
        loggers: /dominus/actuator/loggers
        health: ${HEALTH_CHECK_PATH:/test/alive}
